require: rubocop-performance

inherit_from: './.onkcop-config.yml'

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'tmp/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'tools/**/*'
    - 'test/rails/rails_root/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/BlockDelimiters:
  FunctionalMethods:
    - before
    - let
    - let!
    - subject
    - watch
    - expect
  Exclude:
    # For support original style
    - 'lib/jpmobile/resolver.rb'
    - 'lib/jpmobile/mail.rb'
  EnforcedStyle: braces_for_chaining

Layout/IndentationConsistency:
  EnforcedStyle: normal

Naming/AccessorMethodName:
  Exclude:
    - 'lib/jpmobile/mail.rb'

Naming/ConstantName:
  Exclude:
    - 'lib/jpmobile/datum_conv.rb'

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'test/rails/overrides/spec/spec_helper.rb'

Style/FormatStringToken:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'lib/jpmobile/datum_conv.rb'
    - 'lib/jpmobile/emoticon.rb'
    - 'lib/jpmobile/helpers.rb'
    - 'lib/jpmobile/mail.rb'
    - 'lib/jpmobile/mobile/*'
    - 'lib/jpmobile/fallback_view_selector.rb'
    - 'lib/jpmobile/resolver.rb'
    - 'lib/jpmobile/rack/filter.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/jpmobile/emoticon.rb'
    - 'lib/jpmobile/helpers.rb'
    - 'lib/jpmobile/mail.rb'
    - 'lib/jpmobile/mobile/au.rb'
    - 'lib/jpmobile/mobile/docomo.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/jpmobile/emoticon.rb'
    - 'lib/jpmobile/helpers.rb'
    - 'lib/jpmobile/mail.rb'
    - 'lib/jpmobile/mobile/au.rb'
    - 'lib/jpmobile/mobile/docomo.rb'
    - 'lib/jpmobile/trans_sid.rb'

Layout/LineLength:
  Exclude:
    - '**/*_spec.rb'
    - 'lib/jpmobile/emoticon/z_combine.rb'
    - 'lib/jpmobile/hook_action_view.rb'
    - 'lib/jpmobile/mobile/au.rb'
    - 'lib/jpmobile/mobile/emobile.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/jpmobile/emoticon.rb'
    - 'lib/jpmobile/helpers.rb'
    - 'lib/jpmobile/util.rb'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - 'lib/jpmobile/emoticon.rb'
    - 'lib/tasks/jpmobile_tasks.rake'
    - 'test/rails/overrides/config/routes.rb'

Metrics/BlockNesting:
  Exclude:
    - 'lib/jpmobile/trans_sid.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/jpmobile/filter.rb'
    - 'lib/jpmobile/mail.rb'
    - 'lib/jpmobile/mobile/abstract_mobile.rb'
    - 'lib/jpmobile/mobile/docomo.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/jpmobile/emoticon.rb'
    - 'lib/jpmobile/helpers.rb'
    - 'lib/jpmobile/mail.rb'
    - 'lib/jpmobile/resolver.rb'
    - 'test/rails/overrides/db/migrate/*'

Lint/SuppressedException:
  Exclude:
    - 'lib/jpmobile/emoticon.rb'
    - 'lib/jpmobile/fallback_view_selector.rb'
    - 'lib/jpmobile/position.rb'

Lint/Void:
  Exclude:
    - 'lib/jpmobile/filter.rb'
